<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PackageId>Reza.BuildingBlocks.Validation</PackageId>
        <Description>Validation abstractions and implementations using FluentValidation</Description>
        <PackageTags>validation;fluentvalidation;validator;model-validation;dto</PackageTags>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\BuildingBlocks.Application\BuildingBlocks.Application.csproj"/>
        <ProjectReference Include="..\BuildingBlocks.Results\BuildingBlocks.Results.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="FluentValidation"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions"/>
    </ItemGroup>
</Project>