<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PackageId>Reza.BuildingBlocks.Persistence</PackageId>
        <Description>Persistence abstractions including generic repositories, specifications, and database contexts</Description>
        <PackageTags>persistence;repository;database;orm;specification</PackageTags>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\BuildingBlocks.Application\BuildingBlocks.Application.csproj"/>
        <ProjectReference Include="..\BuildingBlocks.Domain\BuildingBlocks.Domain.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer"/>
        <PackageReference Include="Microsoft.Extensions.Hosting"/>
    </ItemGroup>
</Project>