<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PackageId>Reza.BuildingBlocks.Infrastructure</PackageId>
        <Description>Infrastructure implementations including repositories, unit of work, and external service integrations</Description>
        <PackageTags>infrastructure;repository;unit-of-work;ef-core;sqlserver</PackageTags>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\BuildingBlocks.Application\BuildingBlocks.Application.csproj"/>
        <ProjectReference Include="..\BuildingBlocks.Domain\BuildingBlocks.Domain.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer"/>
        <PackageReference Include="Microsoft.Extensions.Hosting"/>
        <PackageReference Include="MediatR"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions"/>
    </ItemGroup>

</Project>
