<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <PackageId>Reza.BuildingBlocks.Application</PackageId>
        <Description>Application layer abstractions including CQRS, commands, queries, and handlers</Description>
        <PackageTags>cqrs;mediator;application-layer;commands;queries</PackageTags>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\BuildingBlocks.Domain\BuildingBlocks.Domain.csproj" />
      <ProjectReference Include="..\BuildingBlocks.Results\BuildingBlocks.Results.csproj" />
      <ProjectReference Include="..\BuildingBlocks.Specification\BuildingBlocks.Specification.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Utilities\" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions"/>
        <PackageReference Include="Microsoft.Extensions.Options"/>
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Update="Resources\ErrorMessages.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>ErrorMessages.Designer.cs</LastGenOutput>
      </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Resources\ErrorMessages.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>ErrorMessages.resx</DependentUpon>
      </Compile>
    </ItemGroup>

</Project>
