<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GenerateDocumentationFile>True</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\BuildingBlocks.Domain\BuildingBlocks.Domain.csproj" />
      <ProjectReference Include="..\BuildingBlocks.Results\BuildingBlocks.Results.csproj" />
      <ProjectReference Include="..\BuildingBlocks.Specification\BuildingBlocks.Specification.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Utilities\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.16" />
      <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.16" />
    </ItemGroup>

</Project>
