<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PackageId>Reza.BuildingBlocks.Pagination</PackageId>
        <Description>Pagination abstractions and implementations for paged lists and queries</Description>
        <PackageTags>pagination;paged-list;query;filtering;sorting</PackageTags>
    </PropertyGroup>
</Project>